name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cd check-author-associations-service-app/lib/lambdas/checkAssociations && 
        cargo build --release --target x86_64-unknown-linux-musl &&
        cd target/x86_64-unknown-linux-musl/release && 
        mkdir -p lambda && 
        cp bootstrap lambda/
